name: ln_reader
description: An application for reading light novels and web novels of various types

version: 1.0.2+21

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.0
  url_launcher: ^5.0.2
  intl: ^0.15.8
  http: ^0.12.0+2
  html: ^0.14.0
  connectivity: ^0.4.3+2
  esys_flutter_share: ^1.0.2
  interactive_webview:
    git: git@github.com:TSedlar/interactive_webview.git
  shared_preferences: ^0.5.3+1
  battery_indicator: ^0.0.2
  sticky_headers: ^0.1.8
  flutter_speed_dial: ^1.1.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/blank.png
    - assets/html_serve/pdf2text/
    - assets/images/aggregators/
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/abel-regular.ttf
    - family: AdventPro
      fonts:
        - asset: assets/fonts/adventpro-regular.ttf
    - family: Alice
      fonts:
        - asset: assets/fonts/Alice-Regular.ttf
    - family: Almendra
      fonts:
        - asset: assets/fonts/Almendra-Regular.otf
    - family: Amiko
      fonts:
        - asset: assets/fonts/Amiko-Regular.ttf
    - family: Arcon
      fonts:
        - asset: assets/fonts/Arcon-Regular.otf
    - family: Armata
      fonts:
        - asset: assets/fonts/Armata-Regular.otf
    - family: Assistant
      fonts:
        - asset: assets/fonts/Assistant-Regular.otf
    - family: AurulentSans
      fonts:
        - asset: assets/fonts/AurulentSans-Regular.otf
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.otf
    - family: Bellefair
      fonts:
        - asset: assets/fonts/Bellefair-Regular.otf
    - family: CherrySwash
      fonts:
        - asset: assets/fonts/CherrySwash-Regular.otf
    - family: ClearSans
      fonts:
        - asset: assets/fonts/ClearSans-Regular.ttf
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant-Regular.otf
    - family: DidactGothic
      fonts:
        - asset: assets/fonts/DidactGothic-Regular.otf
    - family: Elsie
      fonts:
        - asset: assets/fonts/Elsie-Regular.otf
    - family: FjordOne
      fonts:
        - asset: assets/fonts/FjordOne-Regular.otf
    - family: Gafata
      fonts:
        - asset: assets/fonts/Gafata-Regular.ttf
    - family: Gaspar
      fonts:
        - asset: assets/fonts/Gaspar-Regular.otf
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.otf
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.otf
    - family: Baskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
    - family: Mako
      fonts:
        - asset: assets/fonts/Mako-Regular.ttf
    - family: Mate
      fonts:
        - asset: assets/fonts/Mate-Regular.otf
    - family: OdibeeSans
      fonts:
        - asset: assets/fonts/OdibeeSans-Regular.otf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron.otf
    - family: Quantico
      fonts:
        - asset: assets/fonts/Quantico-Regular.otf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: Sansita
      fonts:
        - asset: assets/fonts/Sansita-Regular.otf
    - family: Soria
      fonts:
        - asset: assets/fonts/Soria.ttf
    - family: Voltaire
      fonts:
        - asset: assets/fonts/Voltaire-Regular.otf
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular_v2.otf